### ISSUE TITLE
Tab support on web and more

### ISSUE THREAD

**Issue by sunilguptasg** [YoussefRaafatNasry/lo_form#5]
I'm unable to get the Tab key to change focus to the next field even with including this code:

if (kIsWeb) {
      document.addEventListener('keydown', (event) => {if (event.type == 'tab') event.preventDefault()});
    }
Can you provide a working code snippet using the sample RegisterForm code which I am using for evaluation?

Also, there seems to be no way to configure a label. I am able to use a Text field, but this does not have the animation in other packages.

**Comment by Leviatanus** [comment]
Hi, If I understood your question correctly, when it comes to configuring a label it can be done via props attribute on LoTextField.
ex.
LoTextField(
loKey: 'example',
...
props: TextFieldProps(
                            decoration: InputDecoration(
                                labelText: 'Label of some text field',
                                ),
                          ),
)
